### ISSUE TITLE
How to configure history module?

### ISSUE THREAD

**Issue by vol1ura** [blocknotes/activeadmin_quill_editor#34]
Hello! Is there any way to add Undo and Redo buttons from history module?

I have tried to insert in field configuration

```ruby
{
  data: {
    options: {
      modules: {
        history: {
          delay: 2000,
          maxStack: 500,
          userOnly: true
        }
      }
    }
  }
}
```

but it doesn't work.

**Comment by blocknotes** [comment]
> Hello! Is there any way to add Undo and Redo buttons from history module?
> 
> I have tried to insert in field configuration

Hey @vol1ura.
I made a check and it seems fine. I tested it using:

```rb
options = { modules: { history: { delay: 0, maxStack: 500, userOnly: true } }, theme: 'snow' }
f.input :description, as: :quill_editor, input_html: { data: { options: options } }
```

With 0 delay it's easier to see the effect.

But the history options don't seem to setup the Undo/Redo buttons. I made some searches with "quilljs undo button" and there are some workarounds to setup these buttons because it's not a standard feature for the editor.

**Comment by vol1ura** [comment]
OK, thank you for answer.
